export const ADD_TO_PLAYLIST="ADD_TO_PLAYLIST"
export const REMOVE_FROM_PLAYLIST="REMOVE_FROM_PLAYLIST"
export const EMPTY_PLAYLIST="EMPTY_PLAYLIST"
export const PRODUCT_LIST="PRODUCT_LIST"
export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"
export const SEARCH_PRODUCT="SEARCH_PRODUCT"
export const SEARCH_MOVIES="SEARCH_MOVIES"
export const CATAGORY_MOVIES="CATAGORY_MOVIES"
export const CATAGORY_PRODUCT="CATAGORY_PRODUCT"





